import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: '11Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="light">
            <body className={inter.className}>
                <Providers>
                    <div className="overflow-hidden w-[100vw] h-[100vh] flex place-content-center  bg-[#F9F9F9]">{children}</div>
                </Providers>
            </body>
        </html>
    );
}
